"""!

PhD research 2023~2026

@title
    ADMET Wrapper — integrates ADMET evaluation into the BioMolExplorer pipeline.

@info
    ADMETWrapper orchestrates molecule loading, property calculation, toxicity
    filtering, classification (BBB/HIA/PGP), result export, and BOILED-Egg plot
    generation.

    Input convention (aligned with the professor's pipeline):
        ChEMBL/DrugBank/{Target}_MOLS.csv   — unique molecules from bioactivity
        ChEMBL/DrugBank/{Target}_SIMS.csv   — similar molecules
        ChEMBL/DrugBank/{Target}_FULL.csv   — union of MOLS + SIMS

    Output:
        ChEMBL/DrugBank/ADMET/{Target}_MOLS.csv  (+sub-CSVs +egg plot)
        ChEMBL/DrugBank/ADMET/{Target}_SIMS.csv  (+sub-CSVs +egg plot)
        ChEMBL/DrugBank/ADMET/{Target}_FULL.csv  (+sub-CSVs +egg plot)

@authors
   - Michel Pires da Silva (michel@cefetmg.br)
   - Alisson Marques da Silva (alisson@cefetmg.br)
   - Alex Gutterres Taranto (taranto@ufsj.edu.br)

@date 2023-2026
@copyright MIT License
"""
# --------------------------------------------------------------------------------------------
import os
import glob
import pandas as pd
# --------------------------------------------------------------------------------------------

# --------------------------------------------------------------------------------------------
from caad.admet import MoleculeEvaluator, BoiledEggPlotter
# --------------------------------------------------------------------------------------------

# The three group suffixes that the DrugBank crawler generates.
_GROUPS = ("MOLS", "SIMS", "FULL")


class ADMETWrapper:
    """
    Orchestrates the full ADMET analysis pipeline for a ChEMBL target,
    processing the three consolidated DrugBank files (MOLS, SIMS, FULL).

    Args:
        drugbank_path:    Absolute path to the DrugBank directory
                          (contains {Target}_MOLS.csv / _SIMS.csv / _FULL.csv).
        output_path:      Absolute path where ADMET results will be saved.
        target:           Target name exactly as used in the CSV filename
                          prefix (e.g. "Acetylcholinesterase").
        verbose:          If True, prints a per-file summary to stdout.
    """

    def __init__(
        self,
        drugbank_path: str,
        output_path: str,
        target: str,
        verbose: bool = False,
    ):
        self.drugbank_path = drugbank_path
        self.output_path   = output_path
        self.target        = target
        self.verbose       = verbose

        os.makedirs(self.output_path, exist_ok=True)

        self.evaluator = MoleculeEvaluator()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _resolve_group_files(self) -> list[tuple[str, str]]:
        """
        Returns a list of (group_suffix, full_csv_path) for each DrugBank
        group file that exists for this target.

        Raises FileNotFoundError if no group file is found at all.
        """
        found = []
        for suffix in _GROUPS:
            path = os.path.join(
                self.drugbank_path, f"{self.target}_{suffix}.csv"
            )
            if os.path.isfile(path):
                found.append((suffix, path))

        if not found:
            raise FileNotFoundError(
                f"No DrugBank group files found for target '{self.target}' "
                f"in {self.drugbank_path}. "
                f"Expected files like '{self.target}_MOLS.csv'."
            )
        return found

    def _load_group(self, csv_path: str) -> pd.DataFrame:
        """
        Loads a DrugBank group CSV and normalises it to
        [molecule_chembl_id, canonical_smiles].

        DrugBank CSVs already have a top-level 'canonical_smiles' column
        (generated by the crawler wrapper), so no dict-parsing is needed.
        """
        df = pd.read_csv(csv_path)

        if "canonical_smiles" in df.columns:
            df = df[["molecule_chembl_id", "canonical_smiles"]].copy()
            df.dropna(subset=["canonical_smiles"], inplace=True)
            return df

        # Fallback: raw ChEMBL format with molecule_structures dict
        if "molecule_structures" in df.columns:
            import ast

            def _extract(cell) -> str | None:
                try:
                    if pd.isna(cell):
                        return None
                    d = ast.literal_eval(cell) if isinstance(cell, str) else cell
                    return d.get("canonical_smiles") if isinstance(d, dict) else None
                except Exception:
                    return None

            df["canonical_smiles"] = df["molecule_structures"].apply(_extract)
            df = df[["molecule_chembl_id", "canonical_smiles"]].copy()
            df.dropna(subset=["canonical_smiles"], inplace=True)
            return df

        raise ValueError(
            f"CSV '{csv_path}' has neither 'canonical_smiles' nor "
            f"'molecule_structures' column. Found: {list(df.columns)}"
        )

    # ------------------------------------------------------------------
    # Pipeline
    # ------------------------------------------------------------------

    def run_pipeline(self) -> dict:
        """
        Runs the full ADMET pipeline for the three DrugBank groups
        (MOLS, SIMS, FULL).

        Returns:
            A summary dict with per-group counts and overall totals.
        """
        group_files = self._resolve_group_files()

        summary = {
            "target":          self.target,
            "groups":          [],
            "total_input":     0,
            "total_processed": 0,
            "total_excluded":  0,
        }

        for suffix, csv_path in group_files:
            df_input       = self._load_group(csv_path)
            rows           = []
            excluded_count = 0

            for _, row in df_input.iterrows():
                smiles = row["canonical_smiles"]
                name   = row["molecule_chembl_id"]

                props = self.evaluator.calculate_properties(smiles)
                if props is None:
                    excluded_count += 1
                    continue

                # Toxicology filter
                if self.evaluator.is_toxic(props["Mol"]):
                    excluded_count += 1
                    continue

                tpsa, logp, mw = props["TPSA"], props["WLOGP"], props["MW"]
                hbd, hba, rb   = props["HBD"],  props["HBA"],   props["RB"]

                bbb = self.evaluator.classify_bbb(tpsa, logp, mw, hbd, rb)
                hia = self.evaluator.classify_hia(tpsa, logp)
                pgp = self.evaluator.predict_pgp(mw, tpsa, logp, hbd)

                rows.append({
                    "canonical_smiles":   smiles,
                    "molecule_chembl_id": name,
                    "TPSA":  round(tpsa, 2),
                    "WLOGP": round(logp, 2),
                    "MW":    round(mw,   2),
                    "HBD":   hbd,
                    "HBA":   hba,
                    "RB":    rb,
                    "BBB":   bbb,
                    "HIA":   hia,
                    "PGP":   pgp,
                })

            results       = pd.DataFrame(rows)
            out_basename  = f"{self.target}_{suffix}"

            self._export_results(results, out_basename)
            self._generate_plot(results, out_basename)

            group_summary = {
                "group":     suffix,
                "input":     len(df_input),
                "processed": len(results),
                "excluded":  excluded_count,
                "bbb_plus":  int((results["BBB"] == "BBB+").sum()) if not results.empty else 0,
                "bbb_minus": int((results["BBB"] == "BBB-").sum()) if not results.empty else 0,
                "hia_plus":  int((results["HIA"] == "HIA+").sum()) if not results.empty else 0,
                "pgp_plus":  int((results["PGP"] == "PGP+").sum()) if not results.empty else 0,
            }
            summary["groups"].append(group_summary)
            summary["total_input"]     += group_summary["input"]
            summary["total_processed"] += group_summary["processed"]
            summary["total_excluded"]  += group_summary["excluded"]

            if self.verbose:
                self._print_summary(group_summary)

        return summary

    # ------------------------------------------------------------------
    # Export & Plot
    # ------------------------------------------------------------------

    def _export_results(self, results: pd.DataFrame, basename: str) -> None:
        """Saves the main results CSV plus filtered sub-CSVs."""
        if results.empty:
            return

        main_path = os.path.join(self.output_path, basename + ".csv")
        results.to_csv(main_path, index=False)

        filters = [
            ('BBB=="BBB+"', basename + "_BBB+"),
            ('BBB=="BBB-"', basename + "_BBB-"),
            ('HIA=="HIA+"', basename + "_HIA+"),
        ]
        for query, out_name in filters:
            subset = results.query(query)[["canonical_smiles", "molecule_chembl_id"]]
            if not subset.empty:
                subset.to_csv(
                    os.path.join(self.output_path, out_name + ".csv"),
                    index=False,
                )

    def _generate_plot(self, results: pd.DataFrame, basename: str) -> None:
        """Renders and saves the BOILED-Egg plot."""
        if results.empty:
            return
        BoiledEggPlotter.plot(
            df=results,
            output_path=self.output_path,
            output_image_file=basename + "_egg.png",
        )

    @staticmethod
    def _print_summary(s: dict) -> None:
        print(f"\n========== ADMET SUMMARY — {s['group']} ==========")
        print(f"Input      : {s['input']}")
        print(f"Excluded   : {s['excluded']}")
        print(f"Processed  : {s['processed']}")
        print(f"BBB+       : {s['bbb_plus']}")
        print(f"BBB-       : {s['bbb_minus']}")
        print(f"HIA+       : {s['hia_plus']}")
        print("=" * 50 + "\n")
